version: "3.6"

networks:
  mercado-network:
    driver: bridge

services:
  traefik:
    container_name: "traefik"
    image: traefik
    ports:
      - "80:80/tcp" # The HTTP port
      - "443:443/tcp" # The HTTPS port
    labels:
      - "traefik.http.routers.traefik.rule=Host(`monitor.acaifood.com.br`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
    command:
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - fominha-network
    restart: always

  frontend:
    container_name: frontend
    image: docker.pkg.github.com/robertveloso/fominha/frontend:latest
    env_file:
      - ./.env.production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`dash.acaifood.com.br`)" #www
      - "traefik.http.routers.frontend.entrypoints=web"
    networks:
      - fominha-network
    restart: always

  backend:
    container_name: backend
    image: docker.pkg.github.com/robertveloso/fominha/backend:latest
    env_file:
      - ./.env.production
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - MONGO_URL=mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.acaifood.com.br`)"
      - "traefik.http.routers.backend.entrypoints=web"
    depends_on:
      - postgres
      - mongo
    networks:
      - fominha-network
    command: node server.js
    restart: always

  queue:
    container_name: queue
    image: docker.pkg.github.com/robertveloso/fominha/backend:latest
    env_file:
      - ./.env.production
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - MONGO_URL=mongo
    depends_on:
      - redis
    networks:
      - fominha-network
    command: node queue.js
    restart: always

  postgres:
    image: postgres
    container_name: postgres
    env_file: .env.production
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - fominha-network

  # mercado-mongo:
  #   image: bitnami/mongodb:latest
  #   container_name: mercado-mongo
  #   env_file: .env.production
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=no
  #     - MONGODB_USERNAME=${MONGO_USER}
  #     - MONGODB_PASSWORD=${MONGO_PASS}
  #     - MONGODB_DATABASE=${MONGO_DB}
  #   ports:
  #     - "${MONGO_PORT}:27017"
  #   networks:
  #     - mercado-network

  redis:
    image: bitnami/redis:latest
    container_name: fominha-redis
    env_file: .env.production
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "${REDIS_PORT}:6379"
    expose:
      - 6379
    networks:
      - fominha-network
