version: '3.6'

networks:
  fominha-network:
    driver: bridge

services:
  fominha-api:
    build: .
    volumes:
      - .:/home/node/api
    env_file: .env
    environment:
      - DB_HOST=fominha-postgres
      - REDIS_HOST=fominha-redis
      # - MONGO_URL=fominha-mongo
    depends_on:
      - fominha-postgres
      # - fominha-mongo
    networks:
      - fominha-network
    container_name: fominha-api
    command: yarn dev:start
    ports:
      - '3333:3333'

  fominha-queue:
    build: .
    env_file: .env
    environment:
      - DB_HOST=fominha-postgres
      - REDIS_HOST=fominha-redis
      # - MONGO_URL=fominha-mongo
    depends_on:
      - fominha-redis
    networks:
      - fominha-network
    container_name: fominha-queue
    command: yarn dev:queue

  fominha-postgres:
    image: postgres
    container_name: fominha-postgres
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    networks:
      - fominha-network

  # fominha-mongo:
  #   image: bitnami/mongodb:latest
  #   container_name: fominha-mongo
  #   env_file: .env
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=no
  #     - MONGODB_USERNAME=${MONGO_USER}
  #     - MONGODB_PASSWORD=${MONGO_PASS}
  #     - MONGODB_DATABASE=${MONGO_DB}
  #   ports:
  #     - '${MONGO_PORT}:27017'
  #   networks:
  #     - fominha-network

  fominha-redis:
    image: bitnami/redis:latest
    container_name: fominha-redis
    env_file: .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '${REDIS_PORT}:6379'
    expose:
      - 6379
    networks:
      - fominha-network
